const PRODUCTS = [
  {id:'honda-ace-125-brake-shoes',brand:'Honda',model:'Ace 125',name:'Brake Shoes',full:'Honda Ace 125 Brake Shoes',price:129.90,category:'Brakes',image:'assets/products/ace-125-brake-shoes.webp',description:'Durable replacement brake shoes for Honda Ace 125, designed for dependable stopping performance and everyday commercial use.'},
  {id:'honda-ace-125-40t-big-sprocket',brand:'Honda',model:'Ace 125',name:'40T Big Sprocket',full:'Honda Ace 125 40T Big Sprocket',price:179.90,category:'Drive',image:'assets/products/125-40t-sprocket.webp',description:'High-quality 40-tooth rear sprocket for Honda Ace 125, built for smooth power transfer and reliable daily riding.'},
  {id:'big-boy-cgl-150-brake-shoes',brand:'Big Boy',model:'CGL 150',name:'Brake Shoes',full:'Big Boy CGL 150 Brake Shoes',price:109.90,category:'Brakes',image:'assets/products/cgl150-brake-shoes.webp',description:'Heavy-duty replacement brake shoes for Big Boy CGL 150, selected for dependable workshop and fleet use.'},
  {id:'big-boy-cgl-150-15t-small-sprocket',brand:'Big Boy',model:'CGL 150',name:'15T Small Sprocket',full:'Big Boy CGL 150 15T Small Sprocket',price:79.90,category:'Drive',image:'assets/products/small-sprocket.webp',description:'15-tooth small sprocket for Big Boy CGL 150, precision-made for smooth drive performance and reliable fitment.'},
  {id:'universal-mirrors',brand:'Universal',model:'Multiple bikes',name:'Mirrors',full:'Universal Mirrors',price:109.90,category:'Accessories',image:'assets/products/universal-mirrors.webp',description:'Durable universal mirrors suited to a wide range of bikes and scooters, helping improve rear visibility.'},
  {id:'big-boy-cgl-150-clutch-lever',brand:'Big Boy',model:'CGL 150 / CG 150',name:'Clutch Lever',full:'Big Boy CGL 150 Clutch Lever',price:99.90,category:'Controls',image:'assets/products/cgl150-clutch-lever.webp',description:'Replacement clutch lever for Big Boy CGL 150 / CG 150, designed for a precise fit and smooth clutch operation.'},
  {id:'honda-ace-125-clutch-lever',brand:'Honda',model:'Ace 125',name:'Clutch Lever',full:'Honda Ace 125 Clutch Lever',price:109.90,category:'Controls',image:'assets/products/ace-125-clutch-lever.webp',description:'High-quality replacement clutch lever for Honda Ace 125, designed for a precise fit and smooth operation.'},
  {id:'honda-ace-125-clutch-cable',brand:'Honda',model:'Ace 125',name:'Clutch Cable',full:'Honda Ace 125 Clutch Cable',price:99.90,category:'Controls',image:'assets/products/ace-125-clutch-cable.webp',description:'Replacement clutch cable for Honda Ace 125, built for smooth clutch engagement and dependable everyday use.'}
];
const money = n => `R ${n.toFixed(2).replace('.', ',')}`;
const getCart = () => { try{return JSON.parse(localStorage.getItem('astroQuote')||'{}')}catch{return {}} };
const saveCart = cart => { localStorage.setItem('astroQuote',JSON.stringify(cart)); updateCartCount(); };
const updateCartCount = () => { const el=document.querySelector('.cart-count'); if(el){const c=getCart(); el.textContent=Object.values(c).reduce((a,b)=>a+b,0); } };
function addToCart(id, qty=1){const cart=getCart(); cart[id]=(cart[id]||0)+Math.max(1,Number(qty)||1); saveCart(cart); const b=document.querySelector(`[data-add="${id}"]`); if(b){const old=b.textContent;b.textContent='Added to quote ✓';setTimeout(()=>b.textContent=old,1200)}}
function whatsappFor(product){return `https://wa.me/27839639857?text=${encodeURIComponent(`Hi Astro Inc, I'd like to enquire about the ${product.full} (${money(product.price)}).`)}`}
function card(p){return `<article class="product-card" data-category="${p.category}" data-search="${(p.full+' '+p.brand+' '+p.model).toLowerCase()}"><a class="product-media" href="product.html?id=${p.id}"><img src="${p.image}" alt="${p.full}" loading="lazy"></a><div class="product-body"><div class="badges"><span class="badge">${p.brand}</span><span class="badge">${p.model}</span></div><h3><a href="product.html?id=${p.id}">${p.name}</a></h3><p class="product-desc">${p.description}</p><div class="product-bottom"><strong class="price">${money(p.price)}</strong><a class="small-link" href="product.html?id=${p.id}">View details →</a></div><button class="add-btn" data-add="${p.id}" type="button">Add to quote request</button></div></article>`}
function renderProducts(limit){const grid=document.querySelector('[data-product-grid]');if(!grid)return; const list=limit?PRODUCTS.slice(0,limit):PRODUCTS;grid.innerHTML=list.map(card).join('');grid.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.add)));}
function initFilters(){const grid=document.querySelector('[data-product-grid]');if(!grid)return;const buttons=[...document.querySelectorAll('.filter')];const search=document.querySelector('[data-search]');const apply=()=>{const active=document.querySelector('.filter.active')?.dataset.filter||'All';const q=(search?.value||'').toLowerCase().trim();grid.querySelectorAll('.product-card').forEach(c=>{const okCat=active==='All'||c.dataset.category===active;const okSearch=!q||c.dataset.search.includes(q);c.style.display=okCat&&okSearch?'':'none'})};buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');apply()}));search?.addEventListener('input',apply)}
function initDetail(){const host=document.querySelector('[data-product-detail]');if(!host)return;const id=new URLSearchParams(location.search).get('id');const p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0];document.title=`${p.full} | Astro Inc`;host.innerHTML=`<div class="detail-grid"><div class="detail-media"><img src="${p.image}" alt="${p.full}"></div><div class="detail-info"><a class="back" href="products.html">← Back to all products</a><div class="badges" style="margin-top:22px"><span class="badge">${p.brand}</span><span class="badge">${p.model}</span><span class="badge">${p.category}</span></div><h1>${p.full}</h1><div class="detail-price">${money(p.price)}</div><p class="detail-desc">${p.description}</p><div class="spec-list"><div class="spec"><span>Brand / fitment</span><strong>${p.brand} ${p.model}</strong></div><div class="spec"><span>Category</span><strong>${p.category}</strong></div><div class="spec"><span>Supply</span><strong>Trade & commercial</strong></div></div><div class="qty-row"><strong>Quantity</strong><div class="qty"><button type="button" data-dec>−</button><input data-qty value="1" inputmode="numeric" aria-label="Quantity"><button type="button" data-inc>+</button></div></div><div class="detail-actions"><button class="btn primary" type="button" data-detail-add>Add to quote request</button><a class="btn ghost" href="${whatsappFor(p)}" target="_blank" rel="noreferrer">WhatsApp about this part</a></div><p class="notice">Prices shown are current supplied product prices. Contact Astro Inc for availability, bulk quantities and trade enquiries.</p></div></div>`;const input=host.querySelector('[data-qty]');host.querySelector('[data-dec]').onclick=()=>input.value=Math.max(1,(Number(input.value)||1)-1);host.querySelector('[data-inc]').onclick=()=>input.value=Math.max(1,(Number(input.value)||1)+1);host.querySelector('[data-detail-add]').onclick=()=>{addToCart(p.id,input.value);location.href='quote.html'};}
function renderQuote(){const host=document.querySelector('[data-quote-items]');if(!host)return;const cart=getCart();const entries=Object.entries(cart).filter(([,q])=>q>0);if(!entries.length){host.innerHTML='<div class="empty"><h3>Your quote request is empty.</h3><p>Add products from the catalogue and they will appear here.</p><a class="btn primary" href="products.html">Browse products</a></div>';document.querySelector('[data-summary]').innerHTML='<p class="notice">No items added yet.</p>';return;}host.innerHTML=entries.map(([id,q])=>{const p=PRODUCTS.find(x=>x.id===id);if(!p)return'';return `<div class="quote-item"><img src="${p.image}" alt="${p.full}"><div><h3>${p.full}</h3><p>${money(p.price)} × ${q}</p><div class="qty" style="margin-top:10px"><button type="button" data-qdec="${id}">−</button><input value="${q}" readonly aria-label="Quantity ${q}"><button type="button" data-qinc="${id}">+</button></div></div><button class="remove" type="button" data-remove="${id}">Remove</button></div>`}).join('');const total=entries.reduce((sum,[id,q])=>{const p=PRODUCTS.find(x=>x.id===id);return sum+(p?.price||0)*q},0);const count=entries.reduce((s,[,q])=>s+q,0);document.querySelector('[data-summary]').innerHTML=`<div class="summary-row"><span>Items</span><strong>${count}</strong></div><div class="summary-row total"><span>Estimated total</span><strong>${money(total)}</strong></div><button class="btn secondary" style="width:100%;margin-top:18px" data-send>Send quote request on WhatsApp</button><p class="notice">This is an enquiry request, not an online checkout. Astro Inc will confirm stock, final pricing and collection/delivery arrangements.</p>`;host.querySelectorAll('[data-qdec]').forEach(b=>b.onclick=()=>{const c=getCart();c[b.dataset.qdec]=Math.max(0,(c[b.dataset.qdec]||1)-1);if(!c[b.dataset.qdec])delete c[b.dataset.qdec];saveCart(c);renderQuote()});host.querySelectorAll('[data-qinc]').forEach(b=>b.onclick=()=>{const c=getCart();c[b.dataset.qinc]=(c[b.dataset.qinc]||0)+1;saveCart(c);renderQuote()});host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const c=getCart();delete c[b.dataset.remove];saveCart(c);renderQuote()});document.querySelector('[data-send]').onclick=()=>{const c=getCart();const lines=Object.entries(c).map(([id,q])=>{const p=PRODUCTS.find(x=>x.id===id);return `• ${q} × ${p.full} — ${money(p.price)} each`});const msg=`Hi Astro Inc, I'd like to request a quote for:\n\n${lines.join('\n')}\n\nEstimated product total: ${money(total)}\n\nPlease confirm availability and final trade pricing.`;window.open(`https://wa.me/27839639857?text=${encodeURIComponent(msg)}`,'_blank')};}
function common(){document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());const btn=document.querySelector('.menu-btn'),nav=document.querySelector('.nav');btn?.addEventListener('click',()=>{const o=nav.classList.toggle('open');btn.setAttribute('aria-expanded',String(o));btn.textContent=o?'Close':'Menu'});updateCartCount()}
document.addEventListener('DOMContentLoaded',()=>{common();renderProducts(document.body.dataset.page==='home'?8:null);initFilters();initDetail();renderQuote()});
